import Head from 'next/head';
import Experience from '../components/Experience/Experience';
import Feature from '../components/Feature/Feature';
import Header from '../components/Header/Header';
import Service from '../components/Service/Service';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Architect</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main>
                <Header />
                <Feature />
                <Experience />
                <Service />
            </main>
        </div>
    );
}
